to-do-app-main/project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
]

to-do-app-main/project/todoapp/urls.py
from django.urls import path
from .views import TaskList,TaskDetail,TaskCreate,TaskUpdate,DeleteView,CustomLoginView,SignUpForm,DeleteTasksView, VerificationView
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', SignUpForm.as_view(), name='register'),
    path('',TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),
    path('delete_tasks/<int:pk>/', DeleteTasksView.as_view(), name='delete_tasks'),
    path('verify-account', VerificationView.as_view(), name='verify'),


    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='todoapp/reset_password.html'), name= 'reset_password'), #submit email form
    path('reset_password_bsent/', auth_views.PasswordResetDoneView.as_view(template_name='todoapp/reset_password_done.html'), name='password_reset_done'), #email sent success message
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='todoapp/reset_password_form.html'), name='password_reset_confirm'), #link to password reset in email
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='todoapp/reset_password_complete.html'),name='password_reset_complete'), #password successfully changed



]

to-do-app-main/project/todoapp/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime

# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    tittle = models.CharField(max_length=200)
    discription = models.TextField(null=True,blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    due_date= models.DateField(null=True)
    due_time = models.TimeField(null=True)


    def __str__(self):
         return self.tittle

    class Meta:
        ordering=['complete']

to-do-app-main/project/todoapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models
from django.forms import ModelForm

class VerifyAccount(forms.ModelForm):
    secret_code = forms.CharField(widget = forms.Textarea(attrs={'placeholder': 'Enter Verification Code'}))
    

class SignUpForm(UserCreationForm):
    email= forms.EmailField(max_length=254,required=True)

    class Meta:
        model = User
        fields = ('username','email','password1','password2')
        
        
class TaskForm(forms.ModelForm):
    due_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))    
    due_time = forms.TimeField(widget=forms.TimeInput(attrs={'type':'time'}))  
    

    class Meta:
        model = models.Task
        fields = ['tittle','discription','complete','due_date','due_time']
        
    def clean_tittle(self):
        tittle = self.cleaned_data['tittle']
        if tittle is None:
            raise forms.ValidationError("Task cannot be empty")
            return tittle   


    
    # def __init__(self,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
    #     self.fields['due_date'].widget.input_type='date'
    #     self.fields['time'].widget.input_type='time'

to-do-app-main/project/todoapp/views.py
from django.shortcuts import render,redirect
from .models import Task
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView,FormView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from .forms import SignUpForm,TaskForm
from datetime import date, timedelta
from todoapp.models import Task
from django.views import View
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse
from django.http import HttpRequest
import random
# Create your views here.


def generate_random_number(num_digits):
    min_value = 10 ** (num_digits - 1)
    max_value = (10 ** num_digits) - 1
    return random.randint(min_value, max_value)

class CustomLoginView(LoginView):
    template_name = 'todoapp/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    def  get_success_url(self):
        return reverse_lazy('tasks')

class VerificationView(View):
    def get(self, request):
        return render(request, 'todoapp/verify.html')  
    def post(self, request):
        verification_data = request.POST.dict()
        secret_code = verification_data.get("secret_code")
        print(secret_code)

        verification_code = request.session.get('verification_code')

        if(verification_code == secret_code):
            return HttpResponse("Codes match")  
        return HttpResponse("Codes do not match")  


class SignUpForm(CreateView):
    template_name ="todoapp/register.html"
    form_class = SignUpForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')

    def form_valid(self,form):
        user = form.save()

        verification_code = self.request.session.get('verification_code')
        
        secret_code = generate_random_number(6)
        verification_code = str(secret_code)
        self.request.session['verification_code'] = verification_code

        subject = 'Todo App: Group 1 app'
        message = "Dear " +user.username +", you have registered successfully. Click http://127.0.0.1:8000/verify-account?id=" + verification_code + " to verify your account!"
        from_email = settings.EMAIL_HOST_USER
        recipient_list = ['deannahbeb@gmail.com','jovinkyomugaso@gmail.com', user.email]
        send_mail(subject, message, from_email, recipient_list, fail_silently=True)

        if user is not None:
            login(self.request,user)
        return super(SignUpForm, self).form_valid(form)
    
    def get(self,*args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(SignUpForm,self).get(*args, **kwargs)    


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name='tasks'
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks']=context['tasks'].filter(
                tittle__startswith=search_input)
                 
        context['search_input'] = search_input
        return context
        
class DeleteTasksView(View):
    def get(self, request):
        cutoff_date = created + timedelta(days=7)  # set cutoff date to 7 days from when task was created
        tasks_to_delete = Task.objects.filter(due_date__gt=cutoff_date)  # find all tasks with due dates after cutoff
        tasks_to_delete.delete()  # delete tasks from database
        return render(request, 'delete_tasks.html')     
    
class TaskDetail(LoginRequiredMixin,DetailView):
    model = Task
    context_object_name= 'task'
    template_name= 'todoapp/task.html'

class TaskCreate(LoginRequiredMixin,CreateView):
    model= Task
    fields = ['tittle','discription','complete','due_date','due_time'] 
    success_url = reverse_lazy('tasks')
    #form_class = TaskForm
    template_name = 'todoapp/task_form.html'

    def form_valid(self,form):
        form.instance.user = self.request.user
        task = form.save(commit=False)
        task.owner = self.request.user
        task.save()
        return super().form_valid(form) 
   
class TaskUpdate(LoginRequiredMixin,UpdateView):
    model= Task
    fields = ['tittle','discription','complete','due_date','due_time']
    success_url = reverse_lazy('tasks')
    #form_class = TaskForm
    template_name = 'todoapp/task_form.html' 
       
class DeleteView(LoginRequiredMixin,DeleteView):
    model= Task
    context_object_name='task'
    success_url = reverse_lazy('tasks') 



    

to-do-app-main/project/todoapp/templates/todoapp/delete_tasks.html
{% extends 'base.html' %}

{% block content %}
  <h2>Tasks Longer than 7 days have ben deleted Successfully</h2>
{% endblock %}

to-do-app-main/project/todoapp/templates/todoapp/login.html
{% extends 'todoapp/main.html'%}

{% block content %}

   
   


<div class="bg-info p-4 mt-2">
   <h1>TO-DO APP</h1><br>
   <h2>Login Form</h2>
</div>
 <div class="card mt-4">
   <div class="card-header">
      Enter your login credentials to login
   </div>
   <div class="card-body">
      <form action="" class="form mb-2" method="POST">
         {% csrf_token %}
         <div class="form-group">
            <label>{{form.username.label}}</label><br>
            <!-- {{form.username}} -->
            <input type="text" name="username" class="form-control">
         </div>
   


         <div class="form-group mb-3">
            <label>{{form.password.label}}</label><br>
            <!-- {{form.password}} -->
            <input type="password" name="password" class="form-control">
         </div>
   
         <div class="d-grid gap-2">
            <!-- <button class="btn btn-primary" type="button">Button</button> -->
            <input class="btn btn-info" type="submit" value="Login" >
          </div>
      </form>
   </div>
   <div class="card-footer">
      <p>Don't have an account? <a class="button" href="{% url  'register' %}"><strong>Register</strong></a></p>
   </div>

   <div class="card-footer">
      <p>Forgot your password? <a class="button" href="{% url  'reset_password' %}"><strong>Reset password</strong></a></p>
   </div>

 </div>
</div>
{% endblock content %}

to-do-app-main/project/todoapp/templates/todoapp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To do app</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    

    <link href = "https://fonts.googleapis.com/css?family=Roboto" rel = "stylesheet">   
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"> </script>  
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js"> </script> 
    <style>  
        
        

        .ui-datepicker-header {  
          background-color: #2196f3;  
          color: white;  
          text-align: center;  
          font-family: 'Roboto';  
          padding: 10px;  
          height: 40px;  
          border-radius: 8px 8px 0px 0px;  
        }  
     
        .ui-datepicker-prev span {  
          display: none;  
        }  
        .ui-datepicker-prev:after {  
          content: "<";  
          font-size: 2rem;  
          float: left;  
          margin-left: 10px;  
          cursor: pointer;  
        }  
        .ui-datepicker-next span {  
          display: none;  
        }  
        .ui-datepicker-next:after {  
          content: ">";  
          float: right;  
          font-size: 2rem;  
          margin-right: 10px;  
          cursor: pointer;  
        }  
        .ui-datepicker-calendar th {  
          padding: 10px;  
          color: #2196f3;  
        }  
        .ui-datepicker-calendar {  
            text-align: center;  
            margin: 0 auto;  
            padding: 8px;  
        }  
        .ui-datepicker-title {  
          padding: 10px;  
        }  
        .ui-datepicker-calendar td {  
          padding: 4px 0px;  
        }  
        .ui-datepicker-calendar .ui-state-default {  
          text-decoration: none;  
          color: black;  
        }  
        .ui-datepicker-calendar .ui-state-active {  
            color: #2196f3;  
        }  
        </style> 

</head>
<body>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
    
</body>
</html>

to-do-app-main/project/todoapp/templates/todoapp/register.html
{% extends 'todoapp/main.html'%}

{% block content %}
<style>


</style>

<div class="bg-info p-4 mt-2">
   <h1>TO-DO APP</h1><br>
   <h1>Register form</h1>
</div>

<div class="card mt-4">
   <div class="card-header">
      Enter your details to register
   </div>
   <div class="card-body">
      <form action="" class="mb-2" method="POST">
         {% csrf_token %}
         <div class="form-group">
            <label>{{form.username.label}}</label>
            <!-- {{form.username}} -->
            <input type="text" name="username" class="form-control">
         </div>
   
   
         <div class="form-group">
            <label>{{form.email.label}}</label>
            <!-- {{form.email}} -->
            <input type="email" name="email" class="form-control">
         </div>
   
   
   
         <div class="form-group">
            <label>{{form.password1.label}}</label>
            <!-- {{form.password1}} -->
            <input type="password" name="password1" class="form-control">
         </div>
   
         <div class="form-group">
            <label>{{form.password2.label}}</label>
            <!-- {{form.password2}} -->
            <input type="password" name="password2" class="form-control">
         </div>
   
         <br>
   
   
         <div class="d-grid gap-2">
            <input class="btn btn-info" type="submit" value="Register">
         </div>
   
      </form>
   </div>

   <div class="card-footer">
      <p> Already have an account? <a class="button" href="{% url 'login'  %}"><strong>Login</strong></a>
      </p>
   </div>

</div>



{% endblock content %}

to-do-app-main/project/todoapp/templates/todoapp/reset_password.html
{% extends 'todoapp/main.html' %}

{% block content %}
<div class="card-header bg-info mb-2">
    <h1>Reset your password</h1>
    <p> Please enter your email and we will send you steps to complete your password reset.</p>

</div>


<div class="card">

    <form method="POST" action="" class="form mb-2">
        {% csrf_token %}
        <div class="form-group  form-control">

        <label>{{form.email.label}}</label> <br>
        {{form.email}} <br><br>
        </div>

        <input class="btn btn-info mt-2 card-footer form-control" type="submit" value="send email"/>
        
        
    </form>

</div>
{% endblock content %}

to-do-app-main/project/todoapp/templates/todoapp/reset_password_complete.html
{% extends 'todoapp/main.html' %}

{% block content %}
<div class="card-header bg-info mb-2 form-control">
    <h1>Password reset complete </h1>

    <p>Go ahead and login with your new password that you have just created</p>
    

</div>
<div class="card-body form-control">
    <a class= "btn form-control bg-info" href="{% url 'login' %}">Login</a>

</div>

{% endblock content %}

to-do-app-main/project/todoapp/templates/todoapp/reset_password_done.html
{% extends 'todoapp/main.html' %}

{% block content %}


<div class="card-header form-control bg-info" > 
    <h1>Password reset sent</h1>

</div>

<div class="card-footer form-control">
    <p>We have sent details and instructions for reset to the email you entered,you should receive them shortly. </p>

    <p>Please make sure it is the password you registered with and you entered it correctly. check your inbox or spam folder</p>
    

</div>

{% endblock content %}

to-do-app-main/project/todoapp/templates/todoapp/reset_password_form.html
{% extends 'todoapp/main.html' %}

{% block content %}
<div class="card-header form-control mb-2 bg-info">
    <h1>Please create your new password</h1>


</div>
<div class="card-body form-control mt-2">
    <form action="" method="POST">

        {%csrf_token%}
    
        {{form}} <br>  <br>
        <input class= "form-control bg-info"type="submit" name="set new password" >
    </form>

</div>

{% endblock content %}

to-do-app-main/project/todoapp/templates/todoapp/task.html
<h1>Task:{{tasks}}</h1>

to-do-app-main/project/todoapp/templates/todoapp/task_confirm_delete.html
{% extends 'todoapp/main.html'%}

{% block content %}
<div class="mt-2">
    <a class="btn  btn-dark" href="{% url 'tasks' %}"> Go back</a>

</div>

<div class="card mt-4">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="card-header">
            <h4>Delete {{task}}</h4>
        </div>
        <div class="card-body">
            <p>Are u sure u want to delete this task?</p>
            <div class="d-grid gap-2">
                <input class="btn btn-danger" value="Proceed to Delete" type="submit">
             </div>
            
        </div>
    </form>
</div>




{% endblock content %}

to-do-app-main/project/todoapp/templates/todoapp/task_form.html
{% extends 'todoapp/main.html'%}

{% block content %}

<div class="header-bar mt-2">
    <a class="btn  btn-dark" href="{% url 'tasks' %}">&#8592; Back</a>
</div>

<div class="card p-4 mt-4">
    <form action="" class="form  form-group" method="POST">
        {% csrf_token %}
        
        <h2 class="form-title">Create a New Task</h2>
        
        <p class="form-description">Please fill in the details below:</p>
        <div>  
            <div id="calendar"></div>
        </div>   
            <script>  
              var currentDate = new Date("{{ form.due_date.value }}");  
              console.log(currentDate);
              function formatDate(dateString) {
                var date = new Date(dateString);
                var year = date.getFullYear();
                var month = String(date.getMonth() + 1).padStart(2, '0');
                var day = String(date.getDate()).padStart(2, '0');
                return year + '-' + month + '-' + day;
              }

              var date = new Date(formatDate(currentDate));

            $('#calendar').datepicker({  
              inline: true,  
              firstDay: 1, 
              showOtherMonths: true,  
              dayNamesMin:['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']  
            });  

            $("#calendar").datepicker("setDate", date);

            //$("#datepicker").datepicker("setDate", currentDate);
            </script> 
        
       <div class="form-group">
        <label>{{form.tittle.label}}</label> <br>
         <!-- {{ form.tittle }} -->
        <input type="text" name="tittle" value="{{form.tittle.value}}" class="form-control" required id="id_tittle">

       </div>


      <div class="form-group">
        <label>{{form.discription.label}}</label> <br>
        <!-- {{form.discription}} -->
      
        <textarea name="discription"  cols="40" rows="10" id="id_discription" class="form-control">{{form.discription.value}}</textarea>
      </div>



      <div class="form-group mt-2 mb-2">
        <label>{{form.complete.label}}</label>
        {{form.complete}}
       
      </div>

      <label>{{form.due_date.label}}</label> <br>
      <input type="date" value={{form.due_date}}><br><br>
      
      <label>{{form.due_time.label}}</label><br>
      <input type="time" value={{form.due_time}}> <br><br>

      <input  class="btn btn-info" type="submit" value="submit" >  <br>
   
    </form>
</div>




{% endblock content %}

to-do-app-main/project/todoapp/templates/todoapp/task_list.html
 {% extends 'todoapp/main.html'%}

{% block content %}


 <div class="header-bar bg-info p-4 mt-2">
      <div class="row">
         <div class="col-md-10">
            <h1>Your To-Do List</h1>
         </div>
         <div class="col-md-2">
            {% if request.user.is_authenticated %}
   
            <a href="{% url 'logout' %}" class="btn btn-dark block pl-4 pr-4 mt-2">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-dark block pl-4 pr-4 mt-2">Login</a> 
            {% endif %} 

         </div>
      </div>
      <h6>Hello {{request.user|title}}</h6>
 </div>
 <div class="alert alert-success mt-3">
   <p style="font-size: 1.2rem;">You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s"}} </p>
 </div>

   <form  method="GET" style="margin-top: 20px; display: flex;">
      <div class="row">
         <div class="col-md-8 col-sm-5 col-xs-5">
            <input type="text" class="form-control pr-2" name="search-area" value="{{search_input}}">
         </div>
         <div class="col-md-4 col-sm-4 col-xs-5 ">
             <input class="btn btn-outline-info" type="submit" value="Search">
         </div>
      </div>
   </form>
   <a  class="btn btn-primary mt-4" href="{% url 'task-create' %}"><strong>Add task</strong> </a>





<div class="card p-4 mt-4">
   {% for task in tasks %}
      
         {% if task.complete %}
            <div class="row">
               <div class="task-complete-icon"></div>
               <i><s><a href="{% url 'task-update' task.id %}">{{task}}</a></s></i>
            </div>
         <hr>
         
         {% else %}
         <div class="row">
            <div class="col-md-4">
               <div class="task-incomplete-icon"></div>
               <a class="text-sm" href="{% url 'task-update' task.id %}">{{task}}</a>
            </div><br>
            <div class="col-md-4">
               {{task.due_date}} {{task.due_time}}
            </div>
            <div class="col-md-4">
               <a class="btn btn-danger btn-sm shadow-sm pl-4 pr-4" href="{% url 'task-delete' task.id %}"> <span class="text-sm">Delete</span> </a>
            </div>      
         </div>
         <hr>
         
      {% endif %}
     
   {% empty %}
     <div class="alert alert-info mt-4">
      No items in list
     </div>
   {% endfor %} 
</div>


{% endblock content %}

to-do-app-main/project/todoapp/templates/todoapp/verify.html
{% extends 'todoapp/main.html'%}

{% block content %}

   

<div class="bg-info p-4 mt-2">
   <h1>TO-DO APP</h1><br>
   <h2>Confirm Account</h2>
</div>
 <div class="card mt-4">
   <div class="card-header">
      Enter your secret code to confirm your account!
   </div>
   <div class="card-body">
      <form action="" class="form mb-2" method="POST">
         {% csrf_token %}
         <div class="form-group">
            <label>Verification Code</label><br>
            <input type="text" readonly name="secret_code" class="form-control" value="{{ request.GET.id }}"  required placeholder="Secret Code">
         </div>
         <br>   
         <div class="d-grid gap-2">
            <input class="btn btn-info" type="submit" value="Verify Account" >
          </div>
          <br>
      </form>
   </div>
   <div class="card-footer">
      <p>Already have an account? <a class="button" href="{% url  'login' %}"><strong>Login</strong></a></p>
   </div>
 </div>
</div>





{% endblock content %}